services:
  shortener:
    image: shortener:latest
    depends_on:
      - cache
      - roach1
      - roach2
      - roach3
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    secrets:
      - source: db_ca_crt
        target: ca.crt
      - source: db_client_root_key
        target: client.root.key
        mode: 0600
      - source: db_client_root_crt
        target: client.root.crt
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - DB_NAME=shortener
      - DB_PORT=26257
      - DB_USER=root
      - DB_HOST=roach-lb
      - BUS_HOST=rabbit-lb
      - BUS_PORT=5672
      - BUS_USER=admin
      - BUS_PASS=admin
      - BUS_QUEUE=shortener_queue
      - CACHE_URL=redis://cache:6379
      - EXTERNAL_HOST=http://localhost:80
      - HMAC_SEED=o4ye93kpdeazj0jad5sg4dghon4v73s1
      - EXTERNAL_DOMAIN=localhost
      - JWKS_URI=http://zitadel:8080/oauth/v2/keys
    networks:
      - usnet
      - authnet
      - busnet
      - dbnet
      - cachenet
    volumes:
      - shortenerLogging:/shortener/logs
