name: Build Docker Image

# on:
#   push:
#     branches:
#       - develop

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/shortener

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set IMAGE_TAG based on branch
        id: set_image_tag
        run: |
          echo "IMAGE_TAG=${IMAGE_NAME}:${GITHUB_SHA}-dev" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker buildx build --load -t $IMAGE_TAG .
          docker push $IMAGE_TAG
